apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-test
  namespace: devops
  labels:
    app: backend-test
spec:
  replicas: 6
  selector:
    matchLabels:
      app: backend-test
  template:
    metadata:
      labels:
        app: backend-test
    spec:
      containers:
      - name: backend-test
        image: 172.20.11.249:8082/backend-test:latest
        imagePullPolicy: Always
        env:
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-test-cm
              key: USERNAME
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: backend-test-sc
              key: APIKEY
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: backend-test
  namespace: devops
  labels:
    app: backend-test
spec:
  selector:
    app: backend-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
          

